server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cafe-database:3306/cafe?serverTimezone=Asia/Seoul
    username: admin
    password: 1234 # 원래는 그냥 올리면 안되지만 테스트를 위해 그대로 커밋합니다.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  cache:
    type: redis

  data:
    redis:
      host: cafe-redis
      port: 6379
    web:
      pageable:
        default-page-size: 10

token:
  secret-key: aslalijhsdfgbakujshdfgaksujdhfg238475rghwegfajhsdfgjasdhfg82347asggasgadsfgagasdghjmhdev43214321asdfasdfqqqqrtfffdbv245tdfzg1

encrypt:
  key: asidfuhaierswufhaoiwurgh3189047oajsdufh923954823ytjsgnaosdkfhjaoig
  salt: 7234567893123454

springdoc:
  swagger-ui:
    version: v1.0.0
  packages-to-scan: com.kimseungjin.cafe
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
