name: Cafe Reformat Code with Google Java Format
on:
  workflow_run:
    workflows: ["Cafe CI and Build with Gradle Jib"]
    types:
      - completed
permissions:
  contents: write
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  replace-google-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--replace --aosp'
